# ---
version: '3'
services:
  agf-app:
    build:
      context: .
      dockerfile: Dockerfile
    image: nginx-deploy-ecs
    deploy:
      resources:
        limits:
          cpus: '0.2'
          memory: 512M
        reservations:
          cpus: '0.1'
          memory: 256M
    container_name: nginx-deploy-ecs
    ports:
      - '80:80'
    restart: always
    networks:
      - agf-net
networks:
  agf-net:
    driver: bridge
